environment:
  PYTHONDONTWRITEBYTECODE: "1"
  APPVEYOR_SAVE_CACHE_ON_ERROR: "true"
  BINSTAR_TOKEN:
    secure: zW96v77uhbDdArc0805i/CDIvVpZvqCJyJ+WgSE1b65nPLO0nGUwmZ9qshUICIba
  matrix:
    - CONDA_INSTALL_LOCN: C:\Miniconda-x64
      CHIMERADIR: C:\chimera

platform:
  - x64

matrix:
  fast_finish: true

cache:
  - "%CHIMERADIR%"

install:
  # Cygwin's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
  - cmd: rmdir C:\cygwin /s /q
  # Add path, activate `conda` and update conda.
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda.exe config --set always_yes yes
  - cmd: conda.exe config --remove-key channels || true
  - cmd: conda.exe config --add channels defaults
  - cmd: conda.exe install -q conda=4.5 conda-build=3.16 git gnuwin32
  - cmd: set PYTHONUNBUFFERED=1
  # Install Chimera if needed
  - cmd: "IF NOT EXIST %CHIMERADIR% bash scripts\\install_chimera.sh"
  - cmd: "IF EXIST %CHIMERADIR% %CHIMERADIR%\\bin\\chimera.exe --version"
  - cmd: "IF EXIST %CHIMERADIR% %CHIMERADIR%\\bin\\chimera.exe --root"
  # Dependencies
  - cmd: conda.exe build purge
  - cmd: conda.exe build -q --python=2.7 conda-recipe --no-test
  # Create specific Python 2 env
  - cmd: conda.exe env remove -n pychimera || true
  - cmd: conda.exe create -n pychimera --use-local python=2.7 pychimera pytest
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat pychimera
  - cmd: conda.exe list

build: off

test_script:
  - cmd: cd tests
  # Chimera loading and enabling
  - cmd: python pychimeratest.py -v pychimera_test*
  # CLI testing; disabled, use `python -m pychimera` if needed
  # - cmd: pytest -v
  - cmd: python -m pychimera -c "print(2+2)"
  - cmd: cd ..
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\deactivate.bat
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat

deploy_script:
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") { $env:conda_upload = 'true' } Else { write-output "Not on a tag on master, won't deploy to anaconda" }
  - cmd: IF "%conda_upload%"=="true" anaconda -t %BINSTAR_TOKEN% upload %PYTHON%/conda-bld/win-*/pychimera-*.tar.bz2 -u insilichem --no-progress --force