#!/usr/bin/env python2
# -*- coding: utf-8 -*-

"""
pychimera - Use UCSF Chimera Python API in a standard interpreter

This is the binary used to call pychimera.
"""

if "__main__" == __name__:
    import pychimera.__main__
    update_dict = pychimera.__main__.run()
    globals().update(update_dict)
